export const drugNames = {
  alprazfam: 'Alprazolam',
  alpraz2: 'Alprazolam 2mg',
  amphet: 'Amphetamine',
  bupe: 'Buprenorphine 8mg',
  cariso: 'Carisoprodol',
  fent: 'Fentanyl',
  hydroco: 'Hydrocodone',
  hydroco10: 'Hydrocodone 10/325mg',
  hydromorph: 'Hydromorphone',
  hydromorph8: 'Hydromorphone 8mg',
  lisdex: 'Lisdexamfetamine',
  metha: 'Methadone',
  methyl: 'Methylphenidate',
  morph: 'Morphine',
  oxy: 'Oxycodone',
  oxy15: 'Oxycodone 15mg',
  oxy30: 'Oxycodone 30mg',
  oxy10: 'Oxycodone 10/325mg',
  oxymorph: 'Oxymorphone',
  tram: 'Tramadol'
}
