name: Lint

on:
  # Run on all pull requests
  pull_request:
    branches: [ main ]
  # Run when pushing to main or develop branches
  push:
    branches: [ main ]
  # Allow manual triggering
  workflow_dispatch:
  # Can be called by other workflows
  workflow_call:

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run ESLint
        run: npm run lint
